-- ============================================================================
-- V1__init_schema.sql — AI Log Analyzer ilk şema
-- Flyway bu dosyayı uygulama açılışında bir kez çalıştırır ve sürümü kaydeder.
-- Şemanın tek doğruluk kaynağı burasıdır; Hibernate yalnızca doğrulama (validate) yapar.
-- ============================================================================

-- Yüklenen log dosyası ve parse özeti (dashboard için sayaçlar denormalize tutulur)
CREATE TABLE log_file (
    id                UUID PRIMARY KEY,
    filename          VARCHAR(255) NOT NULL,
    storage_path      VARCHAR(500),                        -- Ham dosyanın diskte saklandığı yol (sonradan yeniden parse için)
    size_bytes        BIGINT       NOT NULL,
    uploaded_at       TIMESTAMPTZ  NOT NULL,
    detected_format   VARCHAR(30),                         -- SPRING_BOOT / LOG4J / LOGBACK / SYSLOG / UNKNOWN (parse sonrası dolar)
    line_count        INTEGER      NOT NULL DEFAULT 0,
    error_count       INTEGER      NOT NULL DEFAULT 0,
    warn_count        INTEGER      NOT NULL DEFAULT 0,
    parse_error_count INTEGER      NOT NULL DEFAULT 0,      -- Parse edilemeyen satır sayısı (dürüstlük: hiçbir satır sessizce kaybolmaz)
    first_ts          TIMESTAMPTZ,                          -- Logun kapsadığı zaman aralığının başı
    last_ts           TIMESTAMPTZ,                          -- ... ve sonu
    status            VARCHAR(20)  NOT NULL                 -- UPLOADED / PARSED / ANALYZED / FAILED
);

-- Parse edilmiş kayıtlar. Not: INFO/DEBUG seli DB'yi şişirmesin diye ileride WARN+ öncelikli saklanacak.
CREATE TABLE log_entry (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_id       UUID NOT NULL REFERENCES log_file(id) ON DELETE CASCADE,  -- Dosya silinince kayıtları da sil
    ts            TIMESTAMPTZ,
    level         VARCHAR(10),
    logger_class  VARCHAR(300),
    thread        VARCHAR(200),
    message       TEXT,
    exception_type VARCHAR(300),                            -- Örn. NullPointerException (stack trace'ten çıkarılır)
    stack_trace   TEXT,
    fingerprint   VARCHAR(32),                              -- Hata gruplama anahtarı (MD5) — tekrarlanan hata tespiti
    line_number   INTEGER                                   -- Orijinal dosyadaki satır no (kanıt gösterimi için)
);

-- Tekrarlanan hata grupları (Sentry-vari): aynı parmak izine sahip hatalar tek grupta toplanır
CREATE TABLE error_group (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_id          UUID NOT NULL REFERENCES log_file(id) ON DELETE CASCADE,
    fingerprint      VARCHAR(32) NOT NULL,
    exception_type   VARCHAR(300),
    sample_message   TEXT,                                  -- Grubu temsil eden örnek mesaj
    occurrence_count INTEGER     NOT NULL DEFAULT 0,        -- "Aynı hata 300 kez" çıkarımı için
    first_seen       TIMESTAMPTZ,
    last_seen        TIMESTAMPTZ,
    sample_entry_id  BIGINT REFERENCES log_entry(id) ON DELETE SET NULL  -- Temsilci kayıt (silinirse bağ boşalır)
);

-- Yapay zeka analiz sonuçları (tekrarlanabilirlik için model/prompt sürümü ve maliyet de saklanır)
CREATE TABLE analysis (
    id                UUID PRIMARY KEY,
    file_id           UUID NOT NULL REFERENCES log_file(id) ON DELETE CASCADE,
    model             VARCHAR(100),                         -- Örn. gemini-2.5-flash
    prompt_version    VARCHAR(20),                          -- Prompt sürümü (v1, v2...) — kalite karşılaştırması için
    summary           TEXT,
    root_cause        TEXT,
    solution          TEXT,
    priority          VARCHAR(20),                          -- CRITICAL / HIGH / MEDIUM / LOW
    confidence        NUMERIC(3,2),                         -- 0.00 - 1.00 güven seviyesi
    evidence_lines    JSONB,                                -- AI'ın dayandığı satır numaraları, örn. [1042, 1187]
    raw_response      JSONB,                                -- Modelin ham JSON yanıtı (debug + ileride yeni alanlar)
    prompt_tokens     INTEGER,                              -- Maliyet takibi (LLMOps sinyali)
    completion_tokens INTEGER,
    duration_ms       INTEGER,                              -- Analiz süresi (ms)
    created_at        TIMESTAMPTZ NOT NULL
);

-- Log ile sohbet geçmişi (her analiz bağlamında soru-cevap)
CREATE TABLE chat_message (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    analysis_id UUID NOT NULL REFERENCES analysis(id) ON DELETE CASCADE,
    role        VARCHAR(20) NOT NULL,                       -- USER / ASSISTANT
    content     TEXT        NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL
);

-- --- İndeksler: sık kullanılan sorguları hızlandırır ---
CREATE INDEX idx_log_entry_file      ON log_entry(file_id);              -- Bir dosyanın kayıtlarını çekerken
CREATE INDEX idx_log_entry_level     ON log_entry(file_id, level);       -- Seviye filtreli listelemede
CREATE INDEX idx_error_group_file    ON error_group(file_id);            -- Bir dosyanın hata gruplarını çekerken
CREATE INDEX idx_analysis_file       ON analysis(file_id);               -- Bir dosyanın analiz geçmişinde
CREATE INDEX idx_chat_message_analysis ON chat_message(analysis_id);     -- Bir analizin sohbet geçmişinde
